server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 10

  config:
    import: "configserver:"
